"use strict";
exports.__esModule = true;
var MobilePhone_1 = require("./MobilePhone");
var Laptop_1 = require("./Laptop");
var Catalog_1 = require("./Catalog");
var iphoneXS = new MobilePhone_1.MobilePhone("apple iphone xr", "white", 1000);
var iphoneS = new MobilePhone_1.MobilePhone("apple iphone s", "black", 1200);
var galaxyM20 = new MobilePhone_1.MobilePhone("galaxy m20", "blue", 850);
var phonesCatalog = new Catalog_1.Catalog("new catalog of phones");
phonesCatalog.addItem(iphoneXS);
phonesCatalog.addItem(iphoneS);
phonesCatalog.addItem(galaxyM20);
var macbook = new Laptop_1.Laptop("Apple", "Macbook", 1500);
var dell = new Laptop_1.Laptop("dell", "Macbook", 1200);
var laptpsCatalog = new Catalog_1.Catalog("new catalog of laptops");
laptpsCatalog.addItem(macbook);
laptpsCatalog.addItem(dell);
console.log(phonesCatalog.getDetails());
console.log(laptpsCatalog.getDetails());
