"use strict";
exports.__esModule = true;
var IPhoneXRFactory_1 = require("./IPhoneXRFactory");
var IPhoneXSFactory_1 = require("./IPhoneXSFactory");
var IPhoneXSMaxFactory_1 = require("./IPhoneXSMaxFactory");
var myNewIphoneXr = new IPhoneXRFactory_1.IPhoneXRFactory("XR-0001");
var myNewIphoneXs = new IPhoneXSFactory_1.IPhoneXSFactory("XS-0001");
var myNewIphoneXsMax = new IPhoneXSMaxFactory_1.IPhoneXSMaxFactory("XSMax-0001");
myNewIphoneXr.dial("287392783");
myNewIphoneXr.displayConfig();
myNewIphoneXs.dial("287392783");
myNewIphoneXs.displayConfig();
myNewIphoneXsMax.dial("287392783");
myNewIphoneXsMax.displayConfig();
