"use strict";
exports.__esModule = true;
var IPhoneFactory_1 = require("./IPhoneFactory");
var myNewIphoneXr = IPhoneFactory_1.IPhoneFactoryInstance.create(IPhoneFactory_1.IPHONE_TYPES.XR, "XR-0001");
var myNewIphoneXs = IPhoneFactory_1.IPhoneFactoryInstance.create(IPhoneFactory_1.IPHONE_TYPES.XS, "XS-0001");
var myNewIphoneXsMax = IPhoneFactory_1.IPhoneFactoryInstance.create(IPhoneFactory_1.IPHONE_TYPES.XSMax, "XSMax-0001");
myNewIphoneXr.dial("287392783");
myNewIphoneXr.displayConfig();
myNewIphoneXs.dial("287392783");
myNewIphoneXs.displayConfig();
myNewIphoneXsMax.dial("287392783");
myNewIphoneXsMax.displayConfig();
